-- Bookings: hold (pending_verification) → confirmed; cancelled/expired keep
-- history. Integrity rules (overlap incl. buffer, snapshot immutability,
-- booking number) are delivered by #24; this file owns the table shape.
-- Price snapshot columns follow ADR-0005, money ADR-0019, times ADR-0021.

create type public.booking_status as enum (
  'pending_verification',
  'confirmed',
  'cancelled',
  'expired'
);

create type public.booking_invoicing_status as enum (
  'not_invoiced',
  'invoiced',
  'not_invoicable'
);

create table public.bookings (
  booking_id uuid primary key default gen_random_uuid(),
  -- Generated by a sequence-backed function in #24; never by app code.
  booking_number text not null unique,
  booking_company_id uuid not null references public.companies (company_id),
  booking_room_id uuid not null references public.rooms (room_id),
  booking_status public.booking_status not null default 'pending_verification',
  booking_start_at timestamptz not null,
  booking_end_at timestamptz not null,
  booking_participant_count integer not null check (booking_participant_count > 0),
  -- The responsible booker — not an auth user (ADR-0004).
  booking_booker_name text not null,
  booking_booker_email text not null,
  booking_booker_phone text not null,
  booking_reference text,
  booking_practical_notes text,
  booking_internal_note text,
  -- Price snapshot (ADR-0005): frozen at confirmation.
  booking_room_price_ore integer not null check (booking_room_price_ore >= 0),
  booking_discount_percent integer not null default 0
    check (booking_discount_percent between 0 and 100),
  booking_addon_total_ore integer not null default 0 check (booking_addon_total_ore >= 0),
  booking_expected_total_ore integer not null default 0 check (booking_expected_total_ore >= 0),
  booking_cancellation_terms text,
  -- Cancellation (ADR-0006): fee on the member price, set at cancellation time.
  booking_cancelled_at timestamptz,
  booking_cancellation_fee_ore integer,
  -- Hold while the verification code is being entered.
  booking_hold_expires_at timestamptz,
  -- Invoicing (ADR-0014): booking becomes invoicable after end time.
  booking_invoicing_status public.booking_invoicing_status not null default 'not_invoiced',
  booking_invoice_date date,
  booking_invoice_number text,
  booking_invoiced_at timestamptz,
  booking_invoiced_by uuid references auth.users (id),
  booking_created_at timestamptz not null default now(),
  booking_updated_at timestamptz not null default now(),
  check (booking_end_at > booking_start_at)
);

-- Add-ons selected on a booking; unit price frozen at snapshot time.
create table public.booking_addons (
  booking_addon_booking_id uuid not null references public.bookings (booking_id) on delete cascade,
  booking_addon_addon_id uuid not null references public.addons (addon_id),
  booking_addon_price_ore integer not null check (booking_addon_price_ore >= 0),
  primary key (booking_addon_booking_id, booking_addon_addon_id)
);

-- Availability lookups are by room and time.
create index bookings_room_start_idx on public.bookings (booking_room_id, booking_start_at);
create index bookings_company_idx on public.bookings (booking_company_id);

alter table public.bookings enable row level security;
alter table public.booking_addons enable row level security;
