#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Netlify context-scoped environment variables for The Social House booking
# platform (GitHub issue #28, docs/agents/deploy.md). The site itself, the
# `develop` branch deploy, deploy previews and Node 24 are already in place;
# this wizard only writes the values that must never sit in netlify.toml.
#
# Dashboard click paths were written 2026-09-02 from the live dashboards, not
# from the pinned vendor docs. If a page looks different, look for the same
# words on it before assuming the value moved.

TOTAL_STAGES=9
ENV_FILE=".env.local"
SITE_NAME="the-social-house-booking"
DEV_CONTEXTS=(branch-deploy deploy-preview)
PROD_CONTEXTS=(production)
ALL_CONTEXTS=(production branch-deploy deploy-preview)
NETLIFY_SET=() # "KEY (contexts)" written to Netlify this run

# netlify_env KEY VALUE public|secret CONTEXT... writes one variable to the
# linked Netlify site for the given deploy contexts. Secret values are marked
# so the Netlify UI never shows them again. Adds --scope builds when the
# variable is only needed at build time (SENTRY_AUTH_TOKEN).
netlify_env() {
  local key="$1" value="$2" kind="$3"; shift 3
  local -a args=(env:set "$key" "$value" --context "$@" --force)
  [[ "$kind" == "secret" ]] && args+=(--secret)
  [[ "$key" == "SENTRY_AUTH_TOKEN" ]] && args+=(--scope builds)
  if netlify "${args[@]}" >/dev/null 2>&1; then
    NETLIFY_SET+=("$key ($*)")
    printf '  %s✓ set%s Netlify %s for %s\n' "$GREEN" "$RESET" "$key" "$*"
  else
    SKIPPED+=("Netlify $key for $*: netlify env:set $key … --context $*")
    warn "could not set $key for $*; set it by hand later"
  fi
}

banner "Netlify environment variables"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight: Netlify CLI, account, linked site"
say "Every value is written with the Netlify CLI, so it must be logged in as"
say "the account that owns the site, and this folder must be linked to it."
if ! command -v netlify >/dev/null 2>&1; then
  warn "netlify CLI not found. Install it (npm i -g netlify-cli) and rerun."
  exit 1
fi
if ! netlify status >/dev/null 2>&1; then
  warn "not logged in. Run: netlify login   (then rerun this wizard)"
  exit 1
fi
if ! netlify status 2>/dev/null | grep -q "$SITE_NAME"; then
  say "Linking this folder to the $SITE_NAME site on the logged-in account."
  netlify link --name "$SITE_NAME" >/dev/null 2>&1 || {
    warn "could not link. Run: netlify link   and pick $SITE_NAME, then rerun."
    exit 1
  }
fi
netlify status 2>/dev/null | sed 's/\x1b\[[0-9;]*m//g' | grep -E "Email|Current project|Project URL|Admin URL" | sed 's/^/  /'
PROD_URL="https://$SITE_NAME.netlify.app"
DEV_URL="https://develop--$SITE_NAME.netlify.app"
note "production URL: $PROD_URL"
note "develop URL:    $DEV_URL"
say "Contexts written: production ← main; branch-deploy ← develop;"
say "deploy-preview ← pull requests. The last two share the development values."
pause "Correct account and site?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Supabase: development project → branch-deploy + deploy-preview"
say "The development project is named the-social-house-development."
say "If it does not exist yet: New project, that name, region eu-central-1,"
say "and note the database password for the GitHub Environment later."
open_url "https://supabase.com/dashboard/projects"
step "Open the development project → Project Settings (gear, bottom left)."
step "Data API: copy the Project URL (https://<ref>.supabase.co)."
ask DEV_SUPABASE_URL "Development project URL:"
step "API Keys → Publishable key tab: copy the key (starts sb_publishable_)."
ask DEV_SUPABASE_PUBLISHABLE "Development publishable key:"
step "API Keys → Secret keys tab: create one named 'netlify' if none, reveal, copy."
ask_secret DEV_SUPABASE_SECRET "Development secret key (hidden):"
netlify_env NEXT_PUBLIC_SUPABASE_URL "$DEV_SUPABASE_URL" public "${DEV_CONTEXTS[@]}"
netlify_env NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$DEV_SUPABASE_PUBLISHABLE" public "${DEV_CONTEXTS[@]}"
netlify_env SUPABASE_SECRET_KEY "$DEV_SUPABASE_SECRET" secret "${DEV_CONTEXTS[@]}"
pause "Development Supabase values written."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Supabase: production project → production"
say "Same three values from the-social-house-production."
open_url "https://supabase.com/dashboard/projects"
step "Open the production project → Project Settings → Data API: Project URL."
ask PROD_SUPABASE_URL "Production project URL:"
step "API Keys → Publishable key: copy."
ask PROD_SUPABASE_PUBLISHABLE "Production publishable key:"
step "API Keys → Secret keys: create 'netlify' if none, reveal, copy."
ask_secret PROD_SUPABASE_SECRET "Production secret key (hidden):"
netlify_env NEXT_PUBLIC_SUPABASE_URL "$PROD_SUPABASE_URL" public "${PROD_CONTEXTS[@]}"
netlify_env NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$PROD_SUPABASE_PUBLISHABLE" public "${PROD_CONTEXTS[@]}"
netlify_env SUPABASE_SECRET_KEY "$PROD_SUPABASE_SECRET" secret "${PROD_CONTEXTS[@]}"
pause "Production Supabase values written."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Resend: development API key and redirect address"
say "Development deploys send every email to one address instead of the"
say "real recipient (EMAIL_REDIRECT_TO). The key is a separate, revocable one."
open_url "https://resend.com/api-keys"
step "Create API Key → name 'netlify-development', permission 'Sending access',"
step "domain thesocialhouse.dk → Add. Copy it now; Resend shows it once."
ask_secret DEV_RESEND_KEY "Development Resend API key (hidden):"
ask EMAIL_REDIRECT_TO "Address that receives all development email:"
netlify_env RESEND_API_KEY "$DEV_RESEND_KEY" secret "${DEV_CONTEXTS[@]}"
netlify_env EMAIL_REDIRECT_TO "$EMAIL_REDIRECT_TO" public "${DEV_CONTEXTS[@]}"
pause "Development Resend values written."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Resend: production API key"
open_url "https://resend.com/api-keys"
step "Create API Key → name 'netlify-production', permission 'Sending access',"
step "domain thesocialhouse.dk → Add. Copy it now."
ask_secret PROD_RESEND_KEY "Production Resend API key (hidden):"
netlify_env RESEND_API_KEY "$PROD_RESEND_KEY" secret "${PROD_CONTEXTS[@]}"
pause "Production Resend key written."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Resend: webhook for the develop deploy"
say "The app verifies webhook signatures with RESEND_WEBHOOK_SECRET."
say "Deploy previews get unique URLs, so only the develop URL is registered;"
say "previews share the secret but receive no events."
open_url "https://resend.com/webhooks"
step "Add Webhook → Endpoint URL: $DEV_URL/api/webhooks/resend"
step "Events: email.sent, email.delivered, email.delivery_delayed,"
step "email.bounced, email.complained → Add."
step "Open the new webhook → Signing secret → reveal and copy (starts whsec_)."
ask_secret DEV_WEBHOOK_SECRET "Development webhook signing secret (hidden):"
netlify_env RESEND_WEBHOOK_SECRET "$DEV_WEBHOOK_SECRET" secret "${DEV_CONTEXTS[@]}"
pause "Development webhook secret written."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Resend: webhook for production"
open_url "https://resend.com/webhooks"
step "Add Webhook → Endpoint URL: $PROD_URL/api/webhooks/resend"
step "Same five events → Add → open it → Signing secret → copy."
ask_secret PROD_WEBHOOK_SECRET "Production webhook signing secret (hidden):"
netlify_env RESEND_WEBHOOK_SECRET "$PROD_WEBHOOK_SECRET" secret "${PROD_CONTEXTS[@]}"
pause "Production webhook secret written."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Job secret for POST /api/jobs/*"
say "The scheduled reminders function authenticates with a bearer secret."
say "No dashboard: it is generated here. One value for all contexts, and a"
say "copy in .env.local so the route can be called by hand on develop."
if command -v openssl >/dev/null 2>&1; then
  JOB_SECRET=$(openssl rand -hex 32)
else
  JOB_SECRET=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
fi
note "generated a 64-character hex secret"
netlify_env JOB_SECRET "$JOB_SECRET" secret "${ALL_CONTEXTS[@]}"
write_env JOB_SECRET "$JOB_SECRET"
pause "Job secret written."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Sentry: DSN and source-map auth token"
say "One Sentry project serves both environments; APP_ENV becomes the"
say "environment tag. The auth token is build-only and uploads source maps."
ask SENTRY_ORG "Sentry organisation slug (from the URL, e.g. the-social-house):"
ask SENTRY_PROJECT "Sentry project slug (e.g. booking):"
open_url "https://$SENTRY_ORG.sentry.io/settings/projects/$SENTRY_PROJECT/keys/"
step "Client Keys (DSN): copy the DSN (https://…@o….ingest.sentry.io/…)."
ask SENTRY_DSN "Sentry DSN:"
open_url "https://$SENTRY_ORG.sentry.io/settings/auth-tokens/"
step "Create New Token → name 'netlify-sourcemaps' → scopes project:releases"
step "and org:read → Create. Copy it now; it is shown once."
ask_secret SENTRY_AUTH_TOKEN "Sentry auth token (hidden):"
netlify_env NEXT_PUBLIC_SENTRY_DSN "$SENTRY_DSN" public "${ALL_CONTEXTS[@]}"
netlify_env SENTRY_AUTH_TOKEN "$SENTRY_AUTH_TOKEN" secret "${ALL_CONTEXTS[@]}"
open_url "https://$SENTRY_ORG.sentry.io/settings/developer-settings/"
step "Internal integration 'TSH Booking GitHub issues' -> copy the Client Secret."
ask_secret SENTRY_WEBHOOK_SECRET "Sentry webhook client secret (hidden):"
open_url "https://github.com/settings/personal-access-tokens/new"
step "Fine-grained token, repository the-social-house-booking only, permission Issues: read and write."
ask_secret GITHUB_ISSUES_TOKEN "GitHub issues token (hidden):"
netlify_env SENTRY_WEBHOOK_SECRET "$SENTRY_WEBHOOK_SECRET" secret production
netlify_env GITHUB_ISSUES_TOKEN "$GITHUB_ISSUES_TOKEN" secret production
pause "Sentry values written."

# ── Done ──────────────────────────────────────────────────────────────────
finish
(( ${#NETLIFY_SET[@]} )) && note "set ${#NETLIFY_SET[@]} Netlify variable(s):"
for v in "${NETLIFY_SET[@]}"; do note "  - $v"; done
note "Not set here, by design: APP_ENV, NEXT_PUBLIC_SITE_URL, RESEND_FROM live in netlify.toml."
note "Trigger a deploy of develop and main so the new values take effect."
printf '\n'
